[build-system]
requires = ["setuptools>=61.2; python_version >= '3.6'", "setuptools; python_version < '3'", "setuptools_scm[toml]>=3.4.1"]
build-backend = "setuptools.build_meta"

[project]
name = "backports.entry_points_selectable"
authors = [
	{ name = "Jason R. Coombs", email = "jaraco@jaraco.com" },
]
description = "Compatibility shim providing selectable entry points for older implementations"
readme = "README.rst"
classifiers = [
	"Development Status :: 5 - Production/Stable",
	"Intended Audience :: Developers",
	"License :: OSI Approved :: MIT License",
	"Programming Language :: Python :: 3",
]
requires-python = ">=3.8"
dependencies = ['importlib_metadata; python_version < "3.8"']
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/jaraco/backports.entry_points_selectable"

[project.optional-dependencies]
testing = [
	# upstream
	"pytest",
	"pytest-checkdocs >= 2.4",
	"pytest-cov",
	'pytest-mypy; python_implementation != "PyPy"', # workaround for jaraco/skeleton#22
	"pytest-enabler >= 2.2",
	"pytest-ruff >= 0.2.1",

	# local
]
docs = [
	# upstream
	"sphinx >= 3.5",
	# workaround for sphinx/sphinx-doc#11662
	"sphinx < 7.3.7",
	"jaraco.packaging >= 9.3",
	"rst.linker >= 1.9",
	"furo",
	"sphinx-lint",

	# local
]

[tool.setuptools_scm]
