[build-system]
requires = ["setuptools>=56; python_version >= '3.6'", "setuptools; python_version < '3'", "setuptools_scm[toml]>=3.4.1"]
build-backend = "setuptools.build_meta"

[tool.black]
skip-string-normalization = true

[tool.setuptools_scm]
